Birdnet seems to use a particular DB format perch-hoplite. You can interact with it using standard sql libraries:

In [23]:
import sqlite3
import pandas as pd
import numpy as np


In [ ]:
db_path = 'data/train_embeddings_database/hoplite.sqlite' # Replace with the actual path
connection = sqlite3.connect(db_path)

In [2]:
cursor = connection.cursor()
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
print(cursor.fetchall())

[('hoplite_sources',), ('sqlite_sequence',), ('hoplite_embeddings',), ('hoplite_metadata',), ('hoplite_labels',)]


In [55]:
embeddings = pd.read_sql_query("SELECT * from hoplite_embeddings", connection)
embeddings

id  source_idx           offsets
0        1           1  b'\x00\x00\x00B'
1        2           1     b'\x00@\x00E'
2        3           1     b'\x00D\x00G'
3        4           2  b'\x00\x00\x00B'
4        5           2     b'\x00@\x00E'
...    ...         ...               ...
1335  1336         513     b'\x00@\x00E'
1336  1337         514  b'\x00\x00\x00B'
1337  1338         514     b'\x00@\x00E'
1338  1339         515  b'\x00\x00\x00B'
1339  1340         515     b'\x00@\x00E'

[1340 rows x 3 columns]

In [11]:
sources = pd.read_sql_query("SELECT * from hoplite_sources", connection)
sources['source']

0      //NAS/NAS-Files/Datasets/GCW_labeled_samples/T...
1      //NAS/NAS-Files/Datasets/GCW_labeled_samples/T...
2      //NAS/NAS-Files/Datasets/GCW_labeled_samples/T...
3      //NAS/NAS-Files/Datasets/GCW_labeled_samples/T...
4      //NAS/NAS-Files/Datasets/GCW_labeled_samples/T...
                             ...                        
510    //NAS/NAS-Files/Datasets/GCW_labeled_samples/T...
511    //NAS/NAS-Files/Datasets/GCW_labeled_samples/T...
512    //NAS/NAS-Files/Datasets/GCW_labeled_samples/T...
513    //NAS/NAS-Files/Datasets/GCW_labeled_samples/T...
514    //NAS/NAS-Files/Datasets/GCW_labeled_samples/T...
Name: source, Length: 515, dtype: object

In [51]:
sources

id                   dataset  \
0      1  birdnet_analyzer_dataset   
1      2  birdnet_analyzer_dataset   
2      3  birdnet_analyzer_dataset   
3      4  birdnet_analyzer_dataset   
4      5  birdnet_analyzer_dataset   
..   ...                       ...   
510  511  birdnet_analyzer_dataset   
511  512  birdnet_analyzer_dataset   
512  513  birdnet_analyzer_dataset   
513  514  birdnet_analyzer_dataset   
514  515  birdnet_analyzer_dataset   

                                                source  
0    //NAS/NAS-Files/Datasets/GCW_labeled_samples/T...  
1    //NAS/NAS-Files/Datasets/GCW_labeled_samples/T...  
2    //NAS/NAS-Files/Datasets/GCW_labeled_samples/T...  
3    //NAS/NAS-Files/Datasets/GCW_labeled_samples/T...  
4    //NAS/NAS-Files/Datasets/GCW_labeled_samples/T...  
..                                                 ...  
510  //NAS/NAS-Files/Datasets/GCW_labeled_samples/T...  
511  //NAS/NAS-Files/Datasets/GCW_labeled_samples/T...  
512  //NAS/NAS-Files/Datasets/GCW_labeled_samples/T...  
513  //NAS/NAS-Files/Datasets/GCW_labeled_samples/T...  
514  //NAS/NAS-Files/Datasets/GCW_labeled_samples/T...  

[515 rows x 3 columns]

In [113]:
sources.iloc[514]["source"]

'//NAS/NAS-Files/Datasets/GCW_labeled_samples/Training_Data/Train/Positive\\Library_Positive\\B Song\\332685351-4.wav'

In [111]:
embeddings.iloc[1338]

id                        1339
source_idx                 515
offsets       b'\x00\x00\x00B'
Name: 1338, dtype: object

In [98]:
sources['source'].str.contains("A_Song|A Song", regex=True)

0       True
1       True
2       True
3       True
4       True
       ...  
510    False
511    False
512    False
513    False
514    False
Name: source, Length: 515, dtype: bool

In [97]:
np.where(sources['source'].str.contains("A_Song|A Song", regex=True))[0]

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [116]:
A_song = np.where(sources['source'].str.contains("A_Song|A Song", regex=True))[0] + 1
B_song = np.where(sources['source'].str.contains("B_Song|B Song", regex=True))[0] + 1
A_Song_No_Hook = np.where(sources['source'].str.contains("A_Song_No_Hook"))[0] + 1
A_and_B_Song = np.where(sources['source'].str.contains("A_and_B_Song"))[0] + 1

The above are the source ids for each song type, which is not the same as the embedding id.
This is because these ~5-second recordings (longer than 3s) generate more than one embedding per file. 
Also note the +1 to each index: numpy indices begin at 0, while source ids begin at 1.

We'll use all these embedding, though there is some risk that one of them may not overlap with the GCW song.
Now let's use the source ids to get the embedding id we are actually interested in.


In [117]:
embeddings["source_idx"].isin(A_song) | embeddings["source_idx"].isin(A_Song_No_Hook)

0        True
1        True
2        True
3        True
4        True
        ...  
1335    False
1336    False
1337    False
1338    False
1339    False
Name: source_idx, Length: 1340, dtype: bool

In [118]:
A_present = embeddings["source_idx"].isin(A_song) | embeddings["source_idx"].isin(A_and_B_Song)

In [119]:
B_present = embeddings["source_idx"].isin(B_song) | embeddings["source_idx"].isin(A_and_B_Song)

In [121]:
A_present

0        True
1        True
2        True
3        True
4        True
        ...  
1335    False
1336    False
1337    False
1338    False
1339    False
Name: source_idx, Length: 1340, dtype: bool

In [122]:
B_present

0       False
1       False
2       False
3       False
4       False
        ...  
1335     True
1336     True
1337     True
1338     True
1339     True
Name: source_idx, Length: 1340, dtype: bool

In [123]:
labels = np.zeros(shape=(embeddings.shape[0], 2))

In [124]:
labels[A_present, 0] = 1
labels[B_present, 1] = 1

In [ ]:
labels

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [0., 1.],
       [0., 1.],
       [0., 1.]])

In [128]:
np.save("train_labels.npy", labels)

Or you can use google research's more specialized perch-hoplite. The commands I use here, particularly the initial import and db creation statements, are taken from snippets of Birdnet-Analyzer code. After that it seems pretty straightforward

In [4]:
## pip install git+https://github.com/google-research/perch-hoplite.git
# from perch_hoplite.db import interface as hoplite
from perch_hoplite.db import sqlite_usearch_impl

In [ ]:
db_path = 'data/train_embeddings_database/'
embedding_db = sqlite_usearch_impl.SQLiteUsearchDB.create(db_path)

In [6]:
embedding_db.get_embedding_ids()

array([   1,    2,    3, ..., 1338, 1339, 1340])

In [7]:
embedding_db.get_embedding(1)

array([0.     , 0.9517 , 0.11847, ..., 0.4795 , 0.02275, 0.3196 ],
      dtype=float16)

In [33]:
embedding_db.get_embedding(0)

ValueError: Embeddings 0 not found.

In [8]:
embedding_db.get_embedding_source(1)

EmbeddingSource(dataset_name='birdnet_analyzer_dataset', source_id='//NAS/NAS-Files/Datasets/GCW_labeled_samples/Training_Data/Train/Positive\\Keitt_Positive\\A_Song\\S4A01514_20170310_094702_3081.wav', offsets=array([0., 3.], dtype=float16))

Note that numpy uses 0 indexing while perch hoplite starts at 1. Add 1 to the numpy indices

In [39]:
embedding_db.get_embeddings(A_song+1)[1]

array([[0.     , 0.9517 , 0.11847, ..., 0.4795 , 0.02275, 0.3196 ],
       [0.     , 1.498  , 0.2734 , ..., 0.601  , 0.     , 0.3037 ],
       [0.     , 0.4631 , 0.5166 , ..., 0.1382 , 0.277  , 0.59   ],
       ...,
       [0.332  , 1.031  , 0.646  , ..., 0.6807 , 0.02231, 0.93   ],
       [0.3494 , 1.253  , 0.135  , ..., 0.7607 , 0.0661 , 1.386  ],
       [0.042  , 0.404  , 0.3801 , ..., 0.3909 , 0.0972 , 0.6577 ]],
      dtype=float16)

In [43]:
all_embeddings = embedding_db.get_embeddings(embedding_db.get_embedding_ids())[1]

In [131]:
labels.shape

(1340, 2)

In [45]:
all_embeddings.shape

(1340, 1024)

In [129]:
np.save("train_embeddings.npy", all_embeddings)

In [48]:
len(sources['source'])

515

Repeat for test set database

In [1]:
import sqlite3
import pandas as pd
import numpy as np
db_path = 'data/test_embeddings_database/hoplite.sqlite' # Replace with the actual path
connection = sqlite3.connect(db_path)
cursor = connection.cursor()
embeddings = pd.read_sql_query("SELECT * from hoplite_embeddings", connection)

sources = pd.read_sql_query("SELECT * from hoplite_sources", connection)
A_song = np.where(sources['source'].str.contains("A_Song|A Song", regex=True))[0] + 1
B_song = np.where(sources['source'].str.contains("B_Song|B Song", regex=True))[0] + 1
A_Song_No_Hook = np.where(sources['source'].str.contains("A_Song_No_Hook"))[0] + 1
A_and_B_Song = np.where(sources['source'].str.contains("A_and_B_Song"))[0] + 1

A_present = embeddings["source_idx"].isin(A_song) | embeddings["source_idx"].isin(A_and_B_Song)
B_present = embeddings["source_idx"].isin(B_song) | embeddings["source_idx"].isin(A_and_B_Song)
labels = np.zeros(shape=(embeddings.shape[0], 2))
labels[A_present, 0] = 1
labels[B_present, 1] = 1

np.save("test_labels.npy", labels)

In [5]:
db_path = 'data/test_embeddings_database/'
embedding_db = sqlite_usearch_impl.SQLiteUsearchDB.create(db_path)
all_embeddings = embedding_db.get_embeddings(embedding_db.get_embedding_ids())[1]
np.save("test_embeddings.npy", all_embeddings)

In [7]:
all_embeddings

array([[0.     , 0.2205 , 0.0903 , ..., 0.597  , 0.11523, 0.04623],
       [0.     , 0.315  , 0.     , ..., 0.394  , 0.09326, 0.2109 ],
       [0.     , 0.4424 , 0.     , ..., 0.09265, 0.07434, 0.     ],
       ...,
       [0.0286 , 1.386  , 0.41   , ..., 1.23   , 0.     , 0.     ],
       [0.     , 0.6587 , 0.933  , ..., 0.6025 , 0.0542 , 0.5034 ],
       [0.00628, 0.1055 , 0.     , ..., 0.3428 , 0.1232 , 0.     ]],
      dtype=float16)

In [6]:
all_embeddings.shape

(648, 1024)